apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kotoba-sled
  namespace: kotoba
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
  # Vultr VKE default storage class (block storage)
  storageClassName: vultr-block-storage-hdd
